# Generated by Django 3.1.7 on 2021-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210304_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='job',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
